### ISSUE TITLE
Question: Embedding Static Assets Features?

### ISSUE THREAD

**Issue by StevenACoffman** [posener/gitfs#16]
Hello! I really like your library, and have used it on some private projects.
At work, we use [this rubric for evaluating static asset embedding libraries](https://tech.townsourced.com/post/embedding-static-files-in-go/), and I was wondering where gitfs fits on these criteria:

- [ ] [Compression](https://tech.townsourced.com/post/embedding-static-files-in-go/#compression)
- [ ] [Opt. decompression](https://tech.townsourced.com/post/embedding-static-files-in-go/#optional-decompression)
- [x] [Local FS](https://tech.townsourced.com/post/embedding-static-files-in-go/#loading-from-the-local-file-system)
- [x] [go generate](https://tech.townsourced.com/post/embedding-static-files-in-go/#reproducible-builds)
- [x] [No EXE](https://tech.townsourced.com/post/embedding-static-files-in-go/#reproducible-builds)
- [ ] [Config File](https://tech.townsourced.com/post/embedding-static-files-in-go/#config-file)
- [x] [http.FS](https://tech.townsourced.com/post/embedding-static-files-in-go/#http-filesystem-interface)

**Comment by posener** [comment]
Hi, Thanks!
Please read the README and you can also read my blog post: https://posener.github.io/static-files, as there are answers for most of the questions.

Compression is not currently implemented, but it is doable, and could be interesting to implement. The code should be added to the encode and decode functions [here](https://github.com/posener/gitfs/blob/master/internal/binfs/binfs.go#L83)

Optional decompression will be more difficult to add, and is only relevant to part of the use cases.

Local FS is implemented, please see in the README here: https://github.com/posener/gitfs#development

Go generate is [supported](https://github.com/posener/gitfs#binary-packing). Maybe I should add an example.

No EXE: not sure what you mean.

Config File are not supported, and probably not going to be supported - the configuration is currently done by code. 

`http.FileSystem`: supported. this is what `gitfs.New` function returns.

**Comment by StevenACoffman** [comment]
Ah, your blog article is very illuminating. Thanks!
"No EXE" means it doesn’t require a stand-alone executable, which I was fairly certain was the case. I would love to have an example for go generate. I'll file an issue and close this one. The workflow is certainly nicer than some of the others I've used. 

Very much appreciated your response and hard work on an excellent library!

**Comment by posener** [comment]
Cheers, you can also file a bug on compression support.
