### ISSUE TITLE
Error when `go get github.com/posener/gitfs/cmd/gitfs`

### ISSUE THREAD

**Issue by koddr** [posener/gitfs#28]
Catch strange bug on `v1.1.0` (I use Go `v1.13.5`):

```console
$ go get github.com/posener/gitfs/cmd/gitfs

# github.com/posener/gitfs/fsutil
../.go/src/github.com/posener/gitfs/fsutil/diff.go:171:18: too many arguments in call to diff.Format
../.go/src/github.com/posener/gitfs/fsutil/diff.go:171:49: undefined: diff.OptSuppressCommon
```

Ok. Go to `github.com/posener/gitfs/fsutil/diff.go:171:49` ([link](https://github.com/posener/gitfs/blob/f9828d53944f17ae267d7e9db81957a65e65089f/fsutil/diff.go#L171)) and see:

```go
// ...
d := diff.Format(string(aData), string(bData), diff.OptSuppressCommon())
// ...
```

Third arg for function `diff.Format()` is `diff.OptSuppressCommon()` and _probably_ it's wrong.

**Comment by posener** [comment]
Thanks for reporting this!

It was [supposed to be replaced](https://github.com/posener/gitfs/blob/f9828d53944f17ae267d7e9db81957a65e65089f/go.mod#L20) with a forked version of the `diff` package.
I need to understand why this replace statement didn't work.

**Comment by posener** [comment]
Hey,
I think it might be Go module issue, I couldn't find anything in the [docs](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive). In the github issues, it seems like the replace directive should be only used for development: https://github.com/golang/go/issues/31173.

I might make a fix on this repo, meanwhile you can use this workaround:

```bash
$ cd /tmp
$ git clone https://github.com/posener/gitfs
$ cd gitfs
$ go install ./cmd/gitfs
```

Sorry about that! :-)

**Comment by posener** [comment]
@koddr please update to v1.2.0, this is fixed now (worked around by changing posener/diff to its own module"
